#Dummy line for sed
--download-archive '/volume1/main/Easy Youtube-dl/archives/audio.txt'
--datebefore '20210802'
-a '/volume1/main/Easy Youtube-dl/sources/audio_playlists.txt'
-o 'Downloads/Audio/%(playlist_uploader)s/%(playlist_title)s/%(playlist_index)s %(title)s.%(ext)s'
-i
-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio'
--merge-output-format mp4
--write-sub
--all-subs
--convert-subs srt
--add-metadata
--write-description
--write-thumbnail
