#Dummy line for sed
--download-archive '/shared/archives/video.txt'
--datebefore '20260911'
-a '/shared/sources/video_playlists.txt'
-o 'Downloads/Video/%(playlist_uploader)s/%(playlist_title)s/%(title)s %(resolution)s.%(ext)s'
-i
-f 'bestvideo*+bestaudio/best'
--merge-output-format mkv
--all-subs
--embed-subs
--embed-thumbnail
--embed-metadata
--write-description
--write-info-json
